version: "3.9"
    
services:    
  test-frontend: #nome del servizio
    image: mariamengozzi3/my-nodejs-app
    ports:
      - "3000"
    restart: always
    deploy:
       mode: replicated
       replicas: 2