//per visionare la documentazione: http://localhost:3000/doc/
const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/stations.js', './routes/posts.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Post",
            "description": "Endpoints"
        },
        {
            "name": "Station",
            "description": "Endpoints"
        }
    ],
    /* securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
        petstore_auth: {
            type: "oauth2",
            authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
            flow: "implicit",
            scopes: {
                read_pets: "read your pets",
                write_pets: "modify pets in your account"
            }
        }
    }, */
    definitions: {
        Post: {
            $title: "this is the title of my post",
            $description: "this is the description of my post"
        },
        Station: {
            $name: "Central Park",
            $location: { type: "Point", coordinates: [ -73.97, 40.77 ] }
        } 
    }
}

//swaggerAutogen(outputFile, endpointsFiles) if you want not to execute every time that you run the project

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})